name: Publish & Release

on:
  push:
    tags:
      - 'v*'  # 监听版本号 tag 推送

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'

      - run: npm install
      - run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 读取 package.json 信息
        id: pkg
        run: |
          echo "name=$(jq -r .name package.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: 获取本次发布 commit 记录
        id: changelog
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"%s (%an)" > commits.txt
          else
            git log "$PREV_TAG"..HEAD --pretty=format:"%s (%an)" > commits.txt
          fi
          {
            echo "log<<EOF"
            printf "%s\n" "$(cat commits.txt)"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.pkg.outputs.name }}@${{ steps.pkg.outputs.version }}
          body: ${{ steps.changelog.outputs.log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
